[package]
name = "toy-airport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lyon_geom = "1.0.4"
pathfinding = "4.2.1"
